version: 2
jobs:
  build:
    working_directory: ~/coderdojonavan-python
    docker:
    - image: circleci/python:3.7.0
    steps:
    - checkout
    - run: sudo pip install -U mypy
    - run: mypy basics
