version: 2
jobs:
  build:
    working_directory: ~/coderdojonavan-python
    docker:
    - image: circleci/python:3.7.0
    steps:
    - checkout
    - run: sudo pip install -U pylint mypy pycodestyle
    - run: mypy basics
    - run: pylint basics
    - run: pycodestyle basics
